version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: hotel-availability-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb

networks:
  default:
    name: hotelAvailability