version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: hotel-availability-db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  default:
    name: hotelAvailability